CREATE TABLE EMPLOYEE(
EMPLOYEE_ID INTEGER ,
EMP_FIRSTNAME VARCHAR2(30),
EMP_LASTNAME VARCHAR2(30),
DEPARTMENT_ID INTEGER, 
SALARY INTEGER,
EMP_EMAIL VARCHAR2(50)

);

CREATE TABLE DEPARTMENT (
DEPARTMENT_ID INT,
DEPARTMENT_NAME VARCHAR2(50)
);
/
ALTER TABLE EMPLOYEE
ADD (
    CONSTRAINT EMPLOYEE_IDPK PRIMARY KEY(EMPLOYEE_ID)
    );
    /
ALTER TABLE DEPARTMENT 
ADD( 
    CONSTRAINT DEPARTMENT_IDPK PRIMARY KEY (DEPARTMENT_ID)
    );
    /
--Create a sequence and trigger to auto-generate primary key values for both tables
CREATE SEQUENCE EMPLOYEESEQ
    start with 1
    increment by 1;
    /
CREATE SEQUENCE DEPARTMENTSEQ
    start with 1 
    increment by 1;
    /
    
    CREATE OR REPLACE TRIGGER EMPLOYEE_ON_INSERT
    BEFORE INSERT ON EMPLOYEE
    FOR EACH ROW 
    BEGIN 
    SELECT EMPLOYEE_SEQUENCE.NEXTVAL
    INTO :NEW .EMPLOYEE_ID
    FROM DUAL;
    END;
    
 -- ADDING  EMPLOYEES AND DEPARTMENTS 
-- EMPLOYEES 
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME ,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES('1','TAYLOR','PONCE','1','56000','TAYLORPONCE@GMAIL.COM');
/

INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME ,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES('2','EMILY','HIGGINS','3','100000','EMILY.HIGGINS@GMAIL.COM');
/
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME ,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES('3','FAYE','VALENTINE','1','75000','FVALENTINE34@YAHOO.COM');
/
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME ,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES('4','YUKIHIRA','SOMA','1','75000','YUKISOMA08@GMAIL.COM');
/

INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME ,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES('5','REI','AYANAMI','2','80000','AYANAMI_REI@VERIZON.NET');
/
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME ,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL)
VALUES('90','SHINJI','IKARI','2','80000','SHINJI.IKARI1@YAHOO.COM');
/

-- DEPARTMENTS
INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME)
VALUES('1','RESEARCH AND DEVELOPMENT');
/
INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME)
VALUES('2','TESTING');
/
INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME)
VALUES('3','PROJECT MANAGMENT');
/

--Write a prepared statement which prints each department's name and average salary to the console in Eclipse/STS. 
